server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false
    evictionIntervalTimerInMs: 4000
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
